[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "wm-states"
version = "0.1.0"
description = "Working memory states analysis scripts."
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
  "joblib",
  "llvmlite==0.49.*",
  "matplotlib",
  "numba==0.67.*",
  "numpy>=2.3.5,<2.6",
  "pandas",
  "scikit-learn>=1.8,<1.9",
  "scipy",
  "seaborn",
  "statsmodels>=0.14.6",
  "tqdm",
  "tyro",
]

[tool.setuptools]
packages = []
