"""Strict, public request models for the local pipeline dashboard."""
from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from scripts.next.figure_exports import FigureFormat


class RunRequest(BaseModel):
    model_config = ConfigDict(extra='forbid', strict=True)

    name: str = Field(default='Untitled run', min_length=1, max_length=120)
    data_dir: str = 'data/nature'
    cache_dir: str = 'cache/next_run'
    stages: list[str] = Field(default_factory=lambda: [
        'select', 'decode', 'evaluate', 'states', 'activity', 'prepare', 'models',
        'nested-count', 'nested-activity', 'criticality', 'interactions',
    ])
    n_jobs: int = 1
    max_sessions_to_run: int | None = None
    session_list_file: str | None = None
    figure_formats: list[FigureFormat] = Field(default_factory=lambda: ['png'])
    settings: dict[str, dict[str, Any]] = Field(default_factory=dict)
    allow_existing: bool = False

    @field_validator('name', 'data_dir', 'cache_dir')
    @classmethod
    def nonblank(cls, value: str) -> str:
        if not value.strip() or '\x00' in value:
            raise ValueError('must not be blank or contain NUL characters')
        return value

    @field_validator('n_jobs')
    @classmethod
    def workers(cls, value: int) -> int:
        if value == 0:
            raise ValueError('must be a nonzero integer')
        return value

    @field_validator('max_sessions_to_run')
    @classmethod
    def session_limit(cls, value: int | None) -> int | None:
        if value is not None and value < 1:
            raise ValueError('must be positive when set')
        return value

    @field_validator('stages', 'figure_formats')
    @classmethod
    def nonempty_unique(cls, values: list[str]) -> list[str]:
        if not values or len(values) != len(set(values)):
            raise ValueError('must contain at least one value, with no duplicates')
        return values


class TemplateConfig(BaseModel):
    """Reusable run arguments; absent recording paths stay absent on disk."""
    model_config = ConfigDict(extra='forbid', strict=True)

    settings: dict[str, dict[str, Any]]
    stages: list[str]
    n_jobs: int
    max_sessions_to_run: int | None
    figure_formats: list[FigureFormat]
    data_dir: str | None = None
    session_list_file: str | None = None

    @field_validator('data_dir', 'session_list_file')
    @classmethod
    def recording_path(cls, value: str | None, info):
        if value is None:
            if info.field_name == 'data_dir':
                raise ValueError('must be a path string when included; omit it to keep the current data directory')
            return None
        if not value.strip() or '\x00' in value:
            raise ValueError('must not be blank or contain NUL characters')
        return value


class TemplateRequest(BaseModel):
    model_config = ConfigDict(extra='forbid', strict=True)

    name: str = Field(min_length=1, max_length=120)
    description: str = Field(default='', max_length=2000)
    config: TemplateConfig

    @field_validator('name', 'description')
    @classmethod
    def template_text(cls, value: str, info):
        if '\x00' in value or (info.field_name == 'name' and not value.strip()):
            raise ValueError('must not contain NUL characters or have a blank name')
        return value


class SavedTemplate(TemplateRequest):
    """Versioned disk envelope; IDs and timestamps are generated by the server."""
    schema_version: Literal[1]
    id: str = Field(pattern=r'^[0-9a-f]{32}$')
    created_at: str

    @field_validator('created_at')
    @classmethod
    def timestamp(cls, value: str):
        if datetime.fromisoformat(value).tzinfo is None:
            raise ValueError('must include a timezone')
        return value
